version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2222:8080"
      # - "2221-2223:8080"
    environment:
      # inject on secret...
      - SECRET_KEY=

      - MONGO_URL=
      - MONGO_NAME=

      - DB_TYPE=
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASS=
      - DB_NAME=

    # volumes:
    #   # setup file or folder
    #   - /home/bunda/service-name/assets:/app/assets
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
